# Generated by Django 6.0.7 on 2026-08-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F_Activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='metadata',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='descption',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
