# Generated by Django 6.0.8 on 2026-08-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_Followups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
