# Generated by Django 6.0.7 on 2026-08-02 12:54

import A_User.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', A_User.manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(),
        ),
    ]
