# Generated by Django 6.0.7 on 2026-08-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_User', '0002_alter_user_managers_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
