# Generated by Django 6.0.7 on 2026-07-27 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('COLD_CALL', 'Cold Call')], max_length=30)),
                ('service_interest', models.CharField(choices=[('SEO', 'SEO'), ('GOOGLE_ADS', 'Google Ads'), ('META_ADS', 'Meta Ads'), ('SOCIAL_MEDIA', 'Social Media'), ('WEB_DEVELOPMENT', 'Web Development')], max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=30)),
                ('deal_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('next_followup_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='leads_status_94f025_idx'), models.Index(fields=['source'], name='leads_source_805dfa_idx')],
            },
        ),
    ]
